name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter: 1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/undraw_a_day_at_the_park.png
  fonts:
    - family: Segment7Standard
      fonts:
        - asset: assets/segment7standard/Segment7Standard.otf
    - family: Varela
      fonts:
        - asset: assets/varela/VarelaRound-Regular.ttf
